version: '3.7'

x-common-variables:
  minio: &minio-variables
    MINIO_ACCESS_KEY: &access-key mpUvdqn4VpkHyo8
    MINIO_SECRET_KEY: &secret-key FjI124f5er7PkKFsn0UkkfSd
  nid: &nid-variables
    DATASETS_MINIO_ACCESS_KEY: *access-key
    PUBLICATIONS_MINIO_ACCESS_KEY: *access-key
    DATASETS_MINIO_SECRET_KEY: *secret-key
    PUBLICATIONS_MINIO_SECRET_KEY: *secret-key
    DATASETS_MINIO_ENDPOINT: minio-datasets
    PUBLICATIONS_MINIO_ENDPOINT: minio-publications
    DATASETS_MINIO_PORT: &port 9000
    PUBLICATIONS_MINIO_PORT: *port

services:
  nid:
    image: nid
    build:
      context: $PWD/../
      dockerfile: $PWD/../Dockerfile
    ports:
      - 8000:8000
    environment:
      <<: *nid-variables
      LOG_LEVEL: info
    volumes:
      - $PWD/../:/usr/src/app:ro
    working_dir: /usr/src/app
    entrypoint: sh -c
    command:
      - yarn watch
    networks:
      - private
    links:
      - minio-datasets
      - minio-publications
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nid.docker.localhost"
      - traefik.docker.network=public
      - "traefik.port=8000"

  minio-datasets:
    image: minio/minio
    ports:
      - 9001:9000
    environment:
      <<: *minio-variables
    command: server /data
    networks:
      - private
    volumes:
      - $PWD/data/datasets:/data
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:minio-datasets.docker.localhost"
      - traefik.docker.network=public
      - "traefik.port=9000"

  minio-publications:
    image: minio/minio
    ports:
      - 9002:9000
    environment:
      <<: *minio-variables
    command: server /data
    networks:
      - private
    volumes:
      - $PWD/data/publications:/data
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:minio-publications.docker.localhost"
      - traefik.docker.network=public
      - "traefik.port=9000"

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080
    networks:
      - public
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  public:
    ipam:
      config:
        - subnet: 172.16.288.0/24
  private:
    ipam:
      config:
        - subnet: 10.0.288.0/24
